name: OpenWrt All Build

on:
  workflow_dispatch:    # 手动触发

jobs:
  build-all:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    
    steps:
      - name: Trigger hanwckf build
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Redmi-AX6000-hanwckf.yml',
              ref: 'main'
            });
      
      - name: Trigger immortalwrt build
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Redmi-AX6000-immortalwrt21.02.yml',
              ref: 'main'
            });
      
      - name: Trigger padavanonly build
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'Redmi-AX6000-padavanonly.yml',
              ref: 'main'
            });

      - name: Finish
        run: echo "All workflows have been triggered"
